export interface PresetSource {
  name: string;
  domain: string;
  feedUrl: string;
  category: string;
  language: string;
  country: string;
  sourceType: 'OFFICIAL_RSS' | 'APPROVED_WEB_PAGE' | 'OFFICIAL_API';
  trustLevel: 'OFFICIAL' | 'HIGH' | 'MEDIUM';
  attributionName: string;
  description: string;
}

export const REPUTABLE_NEWS_SOURCES: PresetSource[] = [
  // ── BÁO CHÍ VIỆT NAM HÀNG ĐẦU ──
  {
    name: 'VnExpress - Thời Sự',
    domain: 'vnexpress.net',
    feedUrl: 'https://vnexpress.net/rss/thoi-su.rss',
    category: 'news',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'VnExpress',
    description: 'Tin tức thời sự chính trị, kinh tế, xã hội nhanh và chính xác nhất.',
  },
  {
    name: 'VnExpress - Thế Giới',
    domain: 'vnexpress.net',
    feedUrl: 'https://vnexpress.net/rss/the-gioi.rss',
    category: 'world',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'VnExpress',
    description: 'Sự kiện toàn cầu, phân tích quốc tế và diễn biến nóng.',
  },
  {
    name: 'VnExpress - Khoa Học & Vũ Trụ',
    domain: 'vnexpress.net',
    feedUrl: 'https://vnexpress.net/rss/khoa-hoc.rss',
    category: 'science',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'VnExpress',
    description: 'Khám phá khoa học, công nghệ, vũ trụ, phát minh đời sống.',
  },
  {
    name: 'Tuổi Trẻ - Thời Sự',
    domain: 'tuoitre.vn',
    feedUrl: 'https://tuoitre.vn/rss/thoi-su.rss',
    category: 'news',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'Báo Tuổi Trẻ',
    description: 'Báo Tuổi Trẻ - Tin tức nhanh, trung thực, phản ánh đa chiều.',
  },
  {
    name: 'Tuổi Trẻ - Nhịp Sống Trẻ & Đời Sống',
    domain: 'tuoitre.vn',
    feedUrl: 'https://tuoitre.vn/rss/nhip-song-tre.rss',
    category: 'lifestyle',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'Báo Tuổi Trẻ',
    description: 'Câu chuyện truyền cảm hứng, giới trẻ, đời sống xã hội.',
  },
  {
    name: 'Dân Trí - Xã Hội & Đời Sống',
    domain: 'dantri.com.vn',
    feedUrl: 'https://dantri.com.vn/rss/xa-hoi.rss',
    category: 'society',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'Báo Dân Trí',
    description: 'Tin tức xã hội, đời sống dân sinh, phóng sự điều tra nóng.',
  },
  {
    name: 'Thanh Niên - Thời Sự 24h',
    domain: 'thanhnien.vn',
    feedUrl: 'https://thanhnien.vn/rss/thoi-su.rss',
    category: 'news',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'Báo Thanh Niên',
    description: 'Tin tức thời sự trong và ngoài nước từ Báo Thanh Niên.',
  },
  {
    name: 'VietnamNet - Đời Sống & Pháp Luật',
    domain: 'vietnamnet.vn',
    feedUrl: 'https://vietnamnet.vn/rss/doi-song.rss',
    category: 'lifestyle',
    language: 'vi',
    country: 'VN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'VietnamNet',
    description: 'Các vụ việc đời sống, pháp luật, câu chuyện nhân văn.',
  },
  {
    name: 'BBC News Tiếng Việt',
    domain: 'bbc.com/vietnamese',
    feedUrl: 'https://feeds.bbci.co.uk/vietnamese/rss.xml',
    category: 'world',
    language: 'vi',
    country: 'GB',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'BBC News Tiếng Việt',
    description: 'Tin tức quốc tế, phóng sự và góc nhìn độc lập.',
  },

  // ── NGUỒN TIN TỨC & XU HƯỚNG TRUNG QUỐC (ĐÃ KIỂM ĐỊNH KẾT NỐI 100%) ──
  {
    name: 'China Daily - Tin Tức & Đời Sống Trung Quốc',
    domain: 'chinadaily.com.cn',
    feedUrl: 'https://www.chinadaily.com.cn/rss/china_rss.xml',
    category: 'china_news',
    language: 'en',
    country: 'CN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'OFFICIAL',
    attributionName: 'China Daily',
    description: 'Kênh thông tin chính thống hàng đầu về kinh tế, đời sống xã hội và công nghệ Trung Quốc.',
  },
  {
    name: 'China Daily - Xu Hướng & Đời Sống Viral TQ',
    domain: 'chinadaily.com.cn',
    feedUrl: 'https://www.chinadaily.com.cn/rss/lifestyle_rss.xml',
    category: 'china_lifestyle',
    language: 'en',
    country: 'CN',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'China Daily Lifestyle',
    description: 'Tổng hợp các câu chuyện đời sống, giới trẻ, trào lưu và xu hướng mạng Trung Quốc.',
  },
  {
    name: 'SCMP - Xã Hội & Tin Nóng Trung Quốc',
    domain: 'scmp.com',
    feedUrl: 'https://www.scmp.com/rss/2/feed',
    category: 'china_news',
    language: 'en',
    country: 'HK',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'SCMP China',
    description: 'Phân tích đa chiều, phóng sự độc quyền về xã hội và các hiện tượng mạng tại Trung Quốc.',
  },
  {
    name: 'SCMP - Trào Lưu & Văn Hóa Giới Trẻ TQ (Reels/Viral)',
    domain: 'scmp.com',
    feedUrl: 'https://www.scmp.com/rss/4/feed',
    category: 'china_viral',
    language: 'en',
    country: 'HK',
    sourceType: 'OFFICIAL_RSS',
    trustLevel: 'HIGH',
    attributionName: 'SCMP Lifestyle',
    description: 'Các câu chuyện viral, video xu hướng, drama và văn hóa mạng xã hội Trung Quốc.',
  }
];
